version: "3.9"
services:

  raise_postgres:
    image: postgres:16.1-alpine3.19
    container_name: raise_postgres
    restart: no
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: raise
      POSTGRES_PASSWORD: 8zAgqbfbEKzC68MJ
      POSTGRES_DB: DB_RAISE_DEV
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  raise_app:
#    build: .
#    container_name: raise_app
#    restart: always
#    ports:
#      - "8083:8083"
#    depends_on:
#      - postgres
#      - redis

  raise_pgadmin:
    image: dpage/pgadmin4
    container_name: raise_pgadmin4
    restart: no
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin

#  redis:
#    image: redis:7.2.3-alpine
#    container_name: redis
#    restart: always
#    ports:
#      - '6379:6379'
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
#    volumes:
#      - redis-data:/data

  raise_mailhog:
    image: mailhog/mailhog
    container_name: raise_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
  pgadmin_data:
#  redis_data:
#    driver: local