version: "3.9"
services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: raise
      POSTGRES_PASSWORD: 8zAgqbfbEKzC68MJ
      POSTGRES_DB: DB_RAISE_DEV
    volumes:
      - postgres-data:/var/lib/postgresql/data

#  raise_app:
#    build: .
#    container_name: raise_app
#    restart: always
#    ports:
#      - "8083:8083"
#    depends_on:
#      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres-data:
  pgadmin-data: